### PR TITLE
Add @hrittikhere to GCE-India

### PR DESCRIPTION
**Pull request by hrittikhere**

### CODE REVIEW

**Comment by hrittikhere** [comment]
@paramsiddharth can you give this a look? Thanks :)

**Comment by paramsiddharth** [comment]
@hrittikhere Thank you for the PR! :) Let me invite you to the organization and create an onboarding issue for you before we can have this PR merged.

Edit: Done! Please accept the invitation and checkout the issue: https://github.com/gce-india

**Comment by paramsiddharth** [comment]
@hrittikhere Feel free to merge the PR whenever you're ready. Cheers, and welcome to the community! ❤✨

**Comment by hrittikhere** [comment]
Done ⭐💯

**Pull request merged**
